apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: testdefault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/data/metrics'
        prometheus.io/port: '80'
    spec:
      containers:
        - name: nginx
          image: "nginx:1.27.1-alpine"
